### ISSUE TITLE
Sorting order

### ISSUE THREAD

**Issue by clitetailor** [UnwrittenFun/prettier-plugin-svelte#17]
The current default sorting order is "script > style > html". My prefer sorting order is "html > style > script". Is there any option for that?

**Comment by UnwrittenFun** [comment]
Added in v0.6.0, its called `svelteSortOrder` for your preference it would be
```json
{
    "svelteSortOrder": "markup-styles-scripts"
}
```

**Comment by msmith-techempower** [comment]
I must be missing something obvious, but I added a `.prettierrc` to the root of my project and added:

```JS
{
  "svelteSortOrder": "scripts-markup-styles"
}
```

but VSCode is still formatting with the default sort order.

**Comment by ryanatkn** [comment]
See [this issue](https://github.com/UnwrittenFun/svelte-vscode/issues/44) for vscode support. This was the first option added to the prettier plugin, so future options should probably work automatically in vscode once this is resolved.

**Comment by msmith-techempower** [comment]
Thanks @ryanatkn 

Turns out I was missing something obvious - I had ESLint installed and that seemed to be messing with it. When I uninstalled that plugin, it started working with the `.prettierrc` I listed above.
