### ISSUE TITLE
Closing angle bracket differs from prettier HTML.

### ISSUE THREAD

**Issue by hperrin** [UnwrittenFun/prettier-plugin-svelte#21]
Given a tag that has its attributes spread across lines, prettier will add the closing angle bracket on a new line, like this:

```html
<span
  some="long"
  list="of"
  attributes
>
  Content
</span>
```

But prettier-plugin-svelte will put the angle bracket on the line with the last attribute, like this:

```html
<span
  some="long"
  list="of"
  attributes>
  Content
</span>
```

**Comment by hperrin** [comment]
Would there be a way to use Prettier's HTML formatter for HTML in Svelte, or is that not possible because of the templating stuff?

**Comment by UnwrittenFun** [comment]
This will be available under the option `svelteBracketNewLine`, set it to true to get the behaviour you desire there
