### ISSUE TITLE
HTML entities not preserved

### ISSUE THREAD

**Issue by RedHatter** [UnwrittenFun/prettier-plugin-svelte#29]
HTML entities in templates are replaced with their literal equivalents. For example

```
5 &lt; 6
```

is transformed into
```
5 < 6
```

This can cause encoding issues with unicode entities and compile errors with `<` and `>`.

**Comment by UnwrittenFun** [comment]
This is a limitation with the svelte parser atm. See sveltejs/svelte#2714

**Comment by mdorda** [comment]
It seems this issue is back since version `1.2.0` :-/

**Comment by mdorda** [comment]
@Conduitry Could you please open this issue again? For example:

```html
<i data-icon="&#xE04E;">icon</i>
```

id formatted into:

```html
<i data-icon="">icon</i>
```

**Comment by ehrencrona** [comment]
@mdorda Thanks for the bug report! For next time: a new issue would have been better. The bug described in the description of this issue has been fixed; it's only in attribute values where it doesn't work. In any case, I found and fixed the issue.
