### ISSUE TITLE
Unknown node Options

### ISSUE THREAD

**Issue by taylorzane** [UnwrittenFun/prettier-plugin-svelte#38]
The `<svelte:options>` does not have handling and causes prettier-plugin-svelte to throw an error.

The options (and all other `<svelte:*>` elements should be added (or check if they already exist) to the printer.

I'll try to submit a PR for this this afternoon. If someone wants to tackle it instead, go for it.

**Comment by UnwrittenFun** [comment]
Going to tackle this now
