### ISSUE TITLE
option for shortened await blocks

### ISSUE THREAD

**Issue by andrekisi** [UnwrittenFun/prettier-plugin-svelte#46]
According to the [documentation](https://svelte.dev/docs#Await_blocks), the pending status may be skipped. Also, the catch block may be omitted:

```
{#await promise then value}
  <p>The value is {value}</p>
{/await}
```

At the moment prettier enforces this format:
```
{#await promise}

{:then value}
  <p>The value is {value}</p>
{:catch}

{/await}
```

Which leads to `Empty block` warnings. Workaround is adding empty comments, which is not really pretty. 

Could the shorthand syntax be added? 😃

**Comment by UnwrittenFun** [comment]
added in 0.7.0
