### ISSUE TITLE
Prettier.config

### ISSUE THREAD

**Issue by popuguytheparrot** [UnwrittenFun/prettier-plugin-svelte#6]
Can i use prettier.config.js for plugin? 

```js
module.exports = {
  tabWidth: 2,
  semi: true,
  singleQuote: true,
  plugins: ['prettier-plugin-svelte']
};
```

**Comment by UnwrittenFun** [comment]
I think if you just put 'svelte' instead of the full 'prettier-plugin-svelte' and have it installed locally then prettier will pick it up, let me know if that works 🙂

**Comment by UnwrittenFun** [comment]
Going to close this as I've not heard a response, feel free to reopen if its not working still
