### ISSUE TITLE
Configuration help

### ISSUE THREAD

**Issue by davidsavoie1** [UnwrittenFun/prettier-plugin-svelte#74]
Hi! Sorry if this is really basic, but I have difficulties configuring prettier-plugin-svelte with a configuration file in VS Code. The Svelte extension is installed and I created a `prettierrc.json` file like so:
```json
{
  "trailingComma": "es5",
  "tabWidth": 2,
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "printWidth": 80,
  "singleQuote": false,
  "svelteSortOrder" : "scripts-markup-styles",
  "svelteStrictMode": true,
  "svelteBracketNewLine": false,
  "svelteAllowShorthand": false
}
```

Some configuration is for standard Prettier with JS. However, whatever the values I use for the svelte options, it doesn't seem to make any difference when I format a .svelte file. For example, even with `"svelteAllowShorthand: false"`, the shorthand `{id}` won't be reformatted to `id={id}`:

```html
<div class="ui input" class:transparent="{!focussed}" {id}>
```
Thanks for your kind help!

**Comment by RapidOwl** [comment]
I'm having a similar issue. None of my Prettier config changes have any effect on Svelte files, but they work fine in HTML and JavaScript files. I've tried changing the workspace settings in VS Code as well as creating a .prettierrc file.

Svelte extension version 0.9.3
Prettier version 3.18.0

Formatting still works fine so it just looks like Prettier is only working with its default settings for Svelte files.

**Comment by davidsavoie1** [comment]
Well, I've finally found how to configure VSCode to format Svelte files properly. [This article](https://haodong.io/vs-code-svelte-and-prettier-set-up) (_VS Code Set Up_ at the bottom) helped me find the missing piece in the process. I only needed the `svelte-vscode` extension, then specify the default formatter for Svelte files in VS Code settings:
```
{
    ...
    "[svelte]": {
        "editor.defaultFormatter": "JamesBirtles.svelte-vscode"
    }
}
```
Now, when I use the `Format document` command (with keyboard shortcut) or when I save with `Format on save` setting enabled, everything falls neatly into place. Great!

And if, like me, you didn't know how to open the settings as JSON to specify this configuration, when in the settings window, there's a button in the upper right corner that allows to do so.

Seems to be working just fine now... I didn't see any mention of this in this extension's documentation, nor in svelte-vscode one. Would be a great addition!

**Comment by RapidOwl** [comment]
@davidsavoie1 Thanks for this! Weirdly, it doesn't just work with the default Prettier config. I have to create a prettier config file that explicitly sets up the options. But then I guess that's better for working on multiple machines anyway.

**Comment by davidsavoie1** [comment]
To be honest, the Svelte configurations in my `.prettierrc` file don’t seem to make any difference. For example, if I change the `scripts-markup-style` order, everything stays the same. But at least I get proper recognition of Svelte idioms and autoformatting, so I live with the default configurations! 🤘

**Comment by davidsavoie1** [comment]
By the way, `.prettierrc` configurations are working alright. What I didn't know is that, after making a change to this file, I have to restart the Svelte language server. To do so, I can either use the `Svelte: Restart Language Server` command, or restart VS Code altogether. Everything's working fine now.

**Comment by Youenn-Bouglouan** [comment]
Just adding my 2 cents here since I struggled to get this working as well. The minimum configuration that worked for me was:
- install `jamesbirtles.svelte-vscode` VS Code extension
- install `Prettier` VS Code extension
- add a `.prettierrc` config file in your folder (see picture below)
- edit or create the local `.vscode\settings.json` file with he custom svelte formatter info (see picture below)
- **explicitly restart the language server** `Svelte: Restart Language Server` as @davidsavoie1  mentioned just above! This was the bit that was missing for me (several restarts of VS Code did **not** work for me).

Now all Prettier settings that I set in `.prettierrc` work in my `.svelte` file as well.

![image](https://user-images.githubusercontent.com/8404230/82094920-4c0cfa80-96fe-11ea-9155-aaccdaaee692.png)

**Comment by ishen7** [comment]
> 因为我也很难使这个工作正常，所以只在这里加上2美分。对我有用的最低配置是：
> 
> * 安装`jamesbirtles.svelte-vscode`VS Code扩展
> * 安装`Prettier`VS Code扩展
> * `.prettierrc`在您的文件夹中添加配置文件（请参见下图）
> * `.vscode\settings.json`使用自定义的精简格式化程序信息编辑或创建本地文件（请参见下图）
> * **** `Svelte: Restart Language Server`像上面   提到的@ davidsavoie1一样，**明确地重新启动语言服务器**！这是失踪了我（VS代码的多次重新启动并位**没有**工作对我来说）。
> 
> 现在，我`.prettierrc`在`.svelte`文件中设置的所有Prettier设置也都可以使用。
> 
> ![图片](https://user-images.githubusercontent.com/8404230/82094920-4c0cfa80-96fe-11ea-9155-aaccdaaee692.png)

thanks! it works!

**Comment by Shackless** [comment]
In case anyone else stumbles upon this (I wasn't able to enable "Format on Save"): Since the launch of the official svelte vs-code plugin, the defaultFormatter is no longer called `JamesBirtles.svelte-vscode` but `svelte.svelte-vscode`.

So this works for me in `.editor/settings.json`:

```json
  "[svelte]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "svelte.svelte-vscode"
  },
```

**Comment by maciekgrzybek** [comment]
@davidsavoie1 my saviour :D thanks for the tips mate :) I can finally have some proper dev experience :)

**Comment by davidsavoie1** [comment]
> @davidsavoie1 my saviour :D thanks for the tips mate :) I can finally have some proper dev experience :)

My pleasure, really! I’m glad that other developers get to experience the fun I have coding with Svelte! What a pleasant and powerful ride!

**Comment by maciekgrzybek** [comment]
@davidsavoie1 the power of open source :)

**Comment by x4080** [comment]
Hi, I still cannot format .svelte always 
``` there is no formatter for svelte files installed ```

And when I save .svelte files cannot auto format like you guys can, my configs :

Extension Svelte for VS Code 101.10.0 and remove "files.associations": {"*.svelte": "html" }  in vscode settings

My settings.json
```
{
  "[svelte]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "svelte.svelte-vscode"
  }
}
```

What did I miss ?

Thanks

**Comment by dummdidumm** [comment]
Possible reason: #123

**Comment by irg1008** [comment]
OMG. I did change the first one, didn't realize to change the others. Such a stupid mistake. Thanks for pointing it out so fast. And thanks for the awesome plugin!

**Comment by justingolden21** [comment]
Got it working in my settings.json with:

```
"[svelte]": {
        "editor.defaultFormatter": "svelte.svelte-vscode"
    },
```

Note the name of the package is now **svelte**.svelte-vscode. Also, you can open settings.json with ctrl+shift+P then "settings.json" and select the right option:
![image](https://user-images.githubusercontent.com/30274440/130775420-7c6a27be-93ac-4003-a1b6-d1c6af062aaf.png)

My `.prettierrc` file also has:
```
"plugins": ["prettier-plugin-svelte"]
```

Be sure to remember to add commas correctly, and restart VS code for it to take effect.

My `package.json` has:
```
		"prettier": "~2.2.1",
		"prettier-plugin-svelte": "^2.2.0",
```

**Comment by JunsikChoi** [comment]
just change `"svelteStrictMode": true` to `"svelteStrictMode": false`

**Comment by caleb531** [comment]
In my experience, Prettier auto-formatting for *.svelte files works correctly when I do either of the following:

1. Set `"editor.defaultFormatter": "svelte.svelte-vscode"` in my VS Code settings.json for the workspace

OR

2. Set `"svelteStrictMode": false` in my `.prettierrc`, provided that VS Code's `editor.defaultFormatter` is `null` / "None"

However, I have not had any success getting Prettier to format-on-save for both *.svelte files AND other file types (like *.ts`) in VS Code. It has only ever been or or the other: either all files types except for `*.svelte` get formatted, _or_ nothing but `*.svelte` fiels get formatted.

For example, if `+page.ts` gets formatted on save, then `+page.svelte` does not format on save. Or conversely, when `+page.svelte` correctly formats on save, then `+page.ts` won't format on save.

Has anyone had success getting Prettier to apply to both `*.svelte` _and_ non-`*.svelte` files within VS Code?

**Comment by janosh** [comment]
> Has anyone had success getting Prettier to apply to both `*.svelte` _and_ non-`*.svelte` files within VS Code?

Works for me. You can set language specific formatters. I have both the Prettier and Svelte extensions installed and this in my `settings.json`:

```json5
"[javascript][html][typescript]": {
  "editor.defaultFormatter": "esbenp.prettier-vscode",
},
"[svelte]": {
  "editor.defaultFormatter": "svelte.svelte-vscode",
}
```
