### ISSUE TITLE
Unwanted linebreaks

### ISSUE THREAD

**Issue by jakobrosenberg** [UnwrittenFun/prettier-plugin-svelte#85]
I have a line that looks like this.
```html
or simply <code>/</code>.
```
Prettier formats it into this
```html
  or simply
  <code>/</code>
  .
```

The result is a space before the period, which is highly unwanted.

I've had similar issues where I couldn't allow white spaces between tags, but prettier forced them in anyway.

I've tried adding ``a .prettierrc.json``
```json
{
  "preserveWhitespaces": true
}
```
But to no avail.

Is there any way around this?

**Comment by ryanatkn** [comment]
IME it's the biggest outstanding issue. Duplicate of https://github.com/UnwrittenFun/prettier-plugin-svelte/issues/24

**Comment by jakobrosenberg** [comment]
Thanks for the quick reply. I'll close this issue then.

**Comment by ryanatkn** [comment]
I haven't tried it but there's a preprocessor workaround in that thread btw.
